# Site Settings
locale                   : "zh-CN"
title                    : "史少阳｜个人学术主页"
title_separator          : "-"
description              : "北京理工大学车辆工程硕博连读研究生，研究方向为智能车辆规划与控制、风险感知强化学习、模型预测控制和感知不确定性评估。"

url                      : "https://ssyxszsl.github.io"
baseurl                  : ""
repository               : "ssyxszsl/ssyxszsl.github.io"


# Site Author
author:
  name             : "史少阳"
  avatar           : "profile.png"
  bio              : "北京理工大学车辆工程硕博连读研究生，研究智能车辆规划、控制与安全决策，预计于 2027 年 6 月毕业。"
  location         : "北京，中国"
  employer         : "北京理工大学"
  email            : "shishaoyang@bit.edu.cn"
  github           : "ssyxszsl"

  pubmed           :
  googlescholar    :
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  dblp             :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
